networks:
  default:
    external:
      name: macvlanet
services:
  tester0:
    environment:
      LOGDIR: tester0
    image: myfi-tester:1.0
    networks:
      default:
        ipv4_address: 192.168.1.2
    volumes:
    - /home/trx/mifi-experiment/1-validity:/app
  tester1:
    environment:
      LOGDIR: tester1
    image: myfi-tester:1.0
    networks:
      default:
        ipv4_address: 192.168.1.3
    volumes:
    - /home/trx/mifi-experiment/1-validity:/app
  tester2:
    environment:
      LOGDIR: tester2
    image: myfi-tester:1.0
    networks:
      default:
        ipv4_address: 192.168.1.4
    volumes:
    - /home/trx/mifi-experiment/1-validity:/app
  tester3:
    environment:
      LOGDIR: tester3
    image: myfi-tester:1.0
    networks:
      default:
        ipv4_address: 192.168.1.5
    volumes:
    - /home/trx/mifi-experiment/1-validity:/app
  tester4:
    environment:
      LOGDIR: tester4
    image: myfi-tester:1.0
    networks:
      default:
        ipv4_address: 192.168.1.6
    volumes:
    - /home/trx/mifi-experiment/1-validity:/app
  tester5:
    environment:
      LOGDIR: tester5
    image: myfi-tester:1.0
    networks:
      default:
        ipv4_address: 192.168.1.7
    volumes:
    - /home/trx/mifi-experiment/1-validity:/app
  tester6:
    environment:
      LOGDIR: tester6
    image: myfi-tester:1.0
    networks:
      default:
        ipv4_address: 192.168.1.8
    volumes:
    - /home/trx/mifi-experiment/1-validity:/app
  tester7:
    environment:
      LOGDIR: tester7
    image: myfi-tester:1.0
    networks:
      default:
        ipv4_address: 192.168.1.9
    volumes:
    - /home/trx/mifi-experiment/1-validity:/app
  tester8:
    environment:
      LOGDIR: tester8
    image: myfi-tester:1.0
    networks:
      default:
        ipv4_address: 192.168.1.10
    volumes:
    - /home/trx/mifi-experiment/1-validity:/app
  tester9:
    environment:
      LOGDIR: tester9
    image: myfi-tester:1.0
    networks:
      default:
        ipv4_address: 192.168.1.11
    volumes:
    - /home/trx/mifi-experiment/1-validity:/app
version: '2.0'
